### ISSUE TITLE
Using the windows build

### ISSUE THREAD

**Issue by dave-watts** [ImageMagick/ImageMagick-Windows#1]
Hi,

How can the Windows build be used, there is no README or INSTALL, or other information. There is a shell script in the directory but no source files. Bash scripts are not a Windows thing, running the shell script results in a load of errors, eg.

Cloning
fatal: repository 'ttf/.git' does not exist
fatal: Not a git repository (or any of the parent directories): .git

**Comment by dlemstra** [comment]
I have added a document with build instructions: https://github.com/ImageMagick/ImageMagick-Windows/blob/master/Readme.md. I hope this will help you to get ImageMagick building on windows.
