### ISSUE TITLE
configure.exe produces empty MSVC solution

### ISSUE THREAD

**Issue by ogre** [ImageMagick/ImageMagick-Windows#7]
I have build configure.exe and proceed with all steps, but the resulting solution is an empty project.
I tried many different configurations when running configure.exe.
Here is example output file .sln

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2017
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Release|x64 = Release|x64
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
	EndGlobalSection
EndGlobal
```

**Comment by dlemstra** [comment]
Is it possible that you changed the folder where the configure.exe file will be created? And did you follow the instructions from the readme?

**Comment by ogre** [comment]
thanks for fast response !
I did not change folder structure nor move any files.
I also tried to follow readme's but the info is quite sparse. Basically it says to build configure.exe and run it...

Here are paths to configure.exe and resulting solutions:

D:\dev\projs\imagemagick\ImageMagick-Windows-7\VisualMagick\configure\x64\Release\configure.exe

D:\dev\projs\imagemagick\ImageMagick-Windows-7\VisualMagick\configure\x64\VisualDynamicMT.sln

**Comment by dlemstra** [comment]
The `configure.exe` file should be created in the `D:\dev\projs\imagemagick\ImageMagick-Windows-7\VisualMagick\configure` folder. If you move it there you should get the correct solution file. I don't know why the file was not created in the correct folder.

**Comment by ogre** [comment]
OK that fixes it. Thanks !
I think it is very important to bold this in README

**Comment by Jan-E** [comment]
Looks like configure.sln has been compiled as "Release|x64". Even when you want a x64 ImageMagick configure.sln has to be compiled as "Release|Win32":

https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/29233796/job/l3uelac2qe481pqg?fullLog=true#L248

**Comment by ogre** [comment]
Yes, I switched to x64 by habit :)
Anyway, I created pull requests with additional info in readme files. I hope this will save time for others

thanks !

**Comment by Jan-E** [comment]
If you build configure.sln as "Release|Win32" you do not hace to copy configure.exe to the correct location. It might be better to add that to the readme.

**Comment by ogre** [comment]
I think it's better to state what configure.exe really expects, rather than rely on MSVC building exe file to specific location.

**Comment by dlemstra** [comment]
Thanks for your help @Jan-E. We should probably fix this in the configure solution.

**Comment by Jan-E** [comment]
configure.sln has no "Release|x64" option:
https://github.com/ImageMagick/VisualMagick/blob/master/configure/configure.sln
@ogre must have created the x64 Platform manually.
